### ISSUE TITLE
Scaling load

### ISSUE THREAD

**Issue by kibaekkim** [NREL-SIIP/PowerSystems.jl#862] opened 2022-03-04 05:20 UTC
I am reading the RTS-GMLC data by using the following code:

```julia
using Pkg; Pkg.activate(".")
using PowerSystems
using Dates
using TimeSeries

RTS_GMLC_DIR = "../RTS-GMLC/RTS_Data";
rawsys = PowerSystems.PowerSystemTableData(
    joinpath(RTS_GMLC_DIR, "SourceData"),
    100.0,
    joinpath(RTS_GMLC_DIR, "FormattedData", "SIIP", "user_descriptors.yaml"),
    timeseries_metadata_file = joinpath(RTS_GMLC_DIR, "FormattedData", "SIIP", "timeseries_pointers.json"),
    generator_mapping_file = joinpath(RTS_GMLC_DIR, "FormattedData", "SIIP", "generator_mapping.yaml"),
);

sys = System(rawsys; time_series_resolution = Dates.Hour(1));
horizon = 24
interval = Dates.Hour(24);
transform_single_time_series!(sys, horizon, interval);
```

To run this code successfully, I had to remove the following line from `storage.csv`:

```csv
313_STORAGE_1,313_TAIL_STORAGE,0.15,0.075,NA,0.,50
```

Otherwise, the package was not able to parse it.

Then, to see the forecast load, I ran the code below:

```julia
using Plots

loads = get_components(PowerLoad, sys);
total_loads = 0.0
total_ts_loads = zeros(24)
for l in loads
    ts = get_time_series_array(Deterministic, l, "max_active_power"; ignore_scaling_factors=false)
    total_loads += l.max_active_power
    total_ts_loads .+= values(ts)
end
plot(ones(24)*total_loads, label="nominal")
plot!(total_ts_loads, label="forecast")
```

<img width="599" alt="Screen Shot 2022-03-03 at 11 16 26 PM" src="https://user-images.githubusercontent.com/8064547/156703866-f649914f-dbcb-435d-92b6-6386205bec5d.png">

It looks like the scaling was not done properly. What did I miss from the code above?

**Comment by jd-lara** [comment] 2022-03-04 05:27
Thanks for reporting. @claytonpbarrows has been improving the code for the storage, could this be part of the issue? 

About the time series, you are collecting only the 0.0- 1.0 values of the time series. It seems that time series aren't applying the scaling factor. Can you try this to confirm please 


```julia
for l in loads
    ts = get_time_series_array(Deterministic, l, "max_active_power"; ignore_scaling_factors=false)
    total_loads += l.max_active_power
    total_ts_loads .+= values(ts)*l.max_active_power
end
```

**Comment by kibaekkim** [comment] 2022-03-04 15:02
Thanks for the quick response. 
The first suggestion looks correctly scaled, as seen below. But, the second suggestion did not change anything.

<img width="598" alt="Screen Shot 2022-03-04 at 9 01 44 AM" src="https://user-images.githubusercontent.com/8064547/156786949-a066cb1b-6727-4f38-8e39-bca5ea4c207b.png">

**Comment by kibaekkim** [comment] 2022-03-04 15:14
This may not be a question for this repo. As you can see, I am using the RTS-GMLC data, where reactive load forecast does not exist. Does it make sense to scale `max_reactive_power` as well in order to get a reactive load forecast? Do you have any suggestion?

**Comment by jd-lara** [comment] 2022-03-04 16:40
The RTS dataset doesn't have a separate time series for reactive power so it isn't included in the time series dataset. So we advise users to do 

for l in loads
    ts = get_time_series_array(Deterministic, l, "max_active_power"; ignore_scaling_factors=false)
    total_loads += get_max_reactive_power(l)
    total_ts_loads .+= values(ts)*get_max_reactive_power(l)
end
```

Also, it is strongly suggested to use the accessor functions provided rather than the dot access. If your script changes the base power of the system or others, the dot access won't match.

**Comment by kibaekkim** [comment] 2022-03-04 17:45
Thanks @jd-lara ! All my questions have been answered.

I can open a separate issue for parsing `storage.csv`, if you want.

**Comment by jd-lara** [comment] 2022-03-04 18:06
Thanks for using and reporting issues in PowerSystems.jl. Please open an issue for the storage, I will keep this issue open to look into why `get_time_series_values` isn't making the expected conversion.

**Comment by daniel-thom** [comment] 2022-03-04 23:38
I ran the code above and got expected results when passing ignore_scaling_factors to get_time_series_values (true and false). I suspect that something else may be going on.

**Comment by kibaekkim** [comment] 2022-03-07 14:07
@daniel-thom Can you be more specific? What are the expected results? I can confirm that `get_time_series_values` behaves the same as `get_time_series_array` does; that is, I still need to multiply `get_max_reactive_power(l)` to `values(ts)`. Is this expected?

**Comment by daniel-thom** [comment] 2022-03-07 14:47
I'm not sure what the issue is. I'm only addressing the question raised by @jd-lara as to whether the scaling factors are being applied correctly - they are. Can you run this same test?
```
julia> method1 = [get_time_series_values(Deterministic, l, "max_active_power"; ignore_scaling_factors=false) for l in loads];
julia> method2 = [get_time_series_values(Deterministic, l, "max_active_power"; ignore_scaling_factors=true) * get_max_active_power(l) for l in loads];
julia> method1 == method2
true
```

**Comment by jd-lara** [comment] 2022-03-07 17:51
@kibaekkim we can close the issue since it seems to be related to the usage. We need to improve the documentation about the time series.

**Comment by kibaekkim** [comment] 2022-03-07 18:20
So... just to understand the usage correctly, I can use this below:

```julia
for l in loads
    ts = get_time_series_array(Deterministic, l, "max_active_power"; ignore_scaling_factors=false)
    total_loads += get_max_active_power(l)
    total_ts_loads .+= values(ts)*get_max_active_power(l)
end
```

or **equivalently**,

```julia
for l in loads
    ts = get_time_series_values(Deterministic, l, "max_active_power"; ignore_scaling_factors=false)
    total_loads += get_max_active_power(l)
    total_ts_loads .+= values(ts)*get_max_active_power(l)
end
```

That is, both `get_time_series_array` and `get_time_series_values` should return the same value.
And, if I set `ignore_scaling_factors=true`, then it should be

```julia
for l in loads
    ts = get_time_series_values(Deterministic, l, "max_active_power"; ignore_scaling_factors=true)
    total_loads += get_max_active_power(l)
    total_ts_loads .+= values(ts)*get_max_active_power(l)*get_max_active_power(l)
end
```

Is that correct?

**Comment by jd-lara** [comment] 2022-03-07 18:33
You don't need to call `values` when using `get_time_series_values` and don't need to multiply twice by `get_max_active_power` in the last version. 

The difference between `get_time_series_values` and `get_time_series_array` is that `get_time_series_array` returns a time array and `get_time_series_values` returns the values directly without the time stamps.

**Comment by daniel-thom** [comment] 2022-03-07 18:35
The default behavior of _both_ `get_time_series_array` and `get_time_series_values` is to apply the scaling factor multiplier to the time series array. It may read non-straightforwardly, but that is `ignore_scaling_factors = false`. In this case the scaling factor multiplier is `get_max_active_power(l)`. So, you should be able to do this:

```
for l in loads
    ts_vector = get_time_series_values(Deterministic, l, "max_active_power")
    total_loads += get_max_active_power(l)
end
```

In another case above you wanted to get reactive power. For that case you will need to set `ignore_scaling_factors = true` and then apply `get_max_reactive_power` yourself.

**Comment by kibaekkim** [comment] 2022-03-07 18:45
Sorry that I may be circling the issues...

![plot_7](https://user-images.githubusercontent.com/8064547/157097124-42fec71c-8eac-4f2f-b17f-534a995077c6.png)

This figure is obtained by the code below:

```julia
total_loads = zeros(24)
total_ts_loads = zeros(24)
for l in loads
    ts_vector = get_time_series_values(Deterministic, l, "max_active_power")
    total_loads .+= get_max_active_power(l)
    total_ts_loads += ts_vector
end
plot(total_loads, label="nominal")
plot!(total_ts_loads, label="time series")
```

@jd-lara gave me https://github.com/NREL-SIIP/PowerSystems.jl/issues/862#issuecomment-1058841323. I think I am confused now...

**Comment by jd-lara** [comment] 2022-03-07 18:51
@kibaekkim why do you think the figure is incorrect? The max_active_power value in the RTS is calculated as the peak over the whole year and you are grabbing the load curve for January 1 of the data.

**Comment by jd-lara** [comment] 2022-03-07 18:56
@kibaekkim I think that in the RTS the thermal gen capacity is below the whole system load but not the total generation considering Hydro and Renewables. @claytonpbarrows can you confirm?

**Comment by claytonpbarrows** [comment] 2022-03-07 22:52
I addressed the above issue comments WRT the version of RTS-GMLC [here](https://github.com/GridMod/RTS-GMLC/releases/tag/v0.2.2)

**Closed** 2022-03-07 23:28 UTC
Labels: question
