### ISSUE TITLE
`PowerSystems.ReserveUp` not defined

### ISSUE THREAD

**Issue by kdheepak** [NREL-SIIP/PowerSystems.jl#863] opened 2022-03-04 06:00 UTC
I ran the following code twice in the same REPL

```
using PowerSystemsCaseBuilder
using PowerSystems
build_system(SIIPExampleSystems, "5_bus_hydro_wk_sys")
```

and got this error:

![Screen Shot 2022-03-03 at 10 58 16 PM](https://user-images.githubusercontent.com/1813121/156708310-67d19c48-0dc7-477c-9666-91ed2ff4f1ee.png)

**Comment by kdheepak** [comment] 2022-03-04 06:10
Same issue if I try to run this `system = build_system(SIIPExampleSystems, "5_bus_matpower_DA")` twice.

**Comment by jd-lara** [comment] 2022-03-04 06:13
This seems to be an issue when de-serializing the system the second time you build it.

**Comment by daniel-thom** [comment] 2022-03-04 14:26
I can't reproduce. I tried my normal dev environment with local packages as well as a clean environment. This code path is exercised by everyone that runs PSY and PSI unit tests. I suspect that the issue is somehow tied to your environment. Can you provide steps with a clean environment?

Here are the relevant packages from my env.
```
  [2cd47ed4] InfrastructureSystems v1.17.0
  [f00506e0] PowerSystemCaseBuilder v0.4.16
  [bcd98974] PowerSystems v1.19.0
```

**Comment by daniel-thom** [comment] 2022-03-04 14:49
Ok, I can reproduce it by serializing the system with `import PowerSystems` instead of `using PowerSystems`. The first attempt at deserializing fails because the JSON contains `PowerSystems.ReserveUp` instead of just `ReserveUp`. This is an IS bug.

**Comment by daniel-thom** [comment] 2022-03-04 15:06
This will be fixed for new System serializations in the linked IS pull request. It won't fix deserializations of systems that have `"PowerSystems.ReserveUp"` in the JSON. A workaround is to delete `"PowerSystems."` in that string. If this is a widespread problem then we could add a workaround to PSY deserialization code.

**Closed** 2022-03-04 16:12 UTC
Labels: bug
